name: Bot

on:
  schedule:
    #  7, 11, 17 o'clock every day, but UTC.
    - cron: "0 22,2,8 * * *"

jobs:
  save:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "13.14.0"
      - run: yarn install
      - name: tweet
        run: yarn bot
        env:
          CK: ${{ secrets.CK }}
          CS: ${{ secrets.CS }}
          AK: ${{ secrets.AK }}
          AS: ${{ secrets.AS }}
