name: Bot

on:
  push
  # schedule:
  #   #  7, 11, 17 o'clock every day, but UTC.
  #   - cron: "0 22,2,8 * * *"

jobs:
  save:
    name: bot
    runs-on: ubuntu-latest
    env:
      CK: ${{ secrets.CK }}
      CS: ${{ secrets.CS }}
      AK: ${{ secrets.AK }}
      AS: ${{ secrets.AS }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: tweet
        run: |
          hour=$(date "+%-H")
          if [ ${hour} -eq 7 ]; then
            BOT_MENU_TYPE=morning yarn bot
          elif [ ${hour} -eq 11 ]; then
            BOT_MENU_TYPE=lunch yarn bot
          elif [ ${hour} -eq 17 ]; then
            BOT_MENU_TYPE=dinner yarn bot
          else
            echo 'error'
          fi
