name: Scheduler

on:
  schedule:
    #  7, 11, 17 o'clock every day, but UTC.
    - cron: "0 22,2,8 * * *"

jobs:
  save:
    name: download pdf, save menu json
    runs-on: ubuntu-latest
    env:
      REPO: https://kobakazu0429:${{github.token}}@github.com/kobakazu0429/dorm_menu_bot-with_github_actions.git
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        env:
          CK: ${{ secrets.CK }}
          CS: ${{ secrets.CS }}
          AK: ${{ secrets.AK }}
          AS: ${{ secrets.AS }}
        run: |
          hour=$(date "+%-H")
          if [ ${hour} -eq 7 ]; then
            BOT_MENU_TYPE=morning yarn start
          elif [ ${hour} -eq 11 ]; then
            BOT_MENU_TYPE=lunch yarn start
          elif [ ${hour} -eq 17 ]; then
            BOT_MENU_TYPE=dinner yarn start
          else
            echo 'error'
          fi
