name: Manual

on:
  workflow_dispatch:
    inputs:
      yyyymm:
        description: "gen json file from yyyymm (e.g. 202007)"
        required: true

jobs:
  generateJson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "13.14.0"
      - run: yarn install
      - run: yarn cli ${{ github.event.inputs.yyyymm }}
