name: Manual

on:
  workflow_dispatch:
    inputs:
      yyyymm:
        description: "gen json file from yyyymm (e.g. 202007)"
        required: true

jobs:
  generateJson:
    runs-on: ubuntu-latest
    env:
      REPO: https://kobakazu0429:${{github.token}}@github.com/kobakazu0429/dorm_menu_bot-with_github_actions.git
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "13.14.0"
      - run: yarn install
      - run: yarn cli ${{ github.event.inputs.yyyymm }}
      - name: run multi command
        run: |
          git config --global user.email "someone@sample.com"
          git config --global user.name "github workflow"
          git remote set-url origin ${REPO}
          git status
          git add .
          git diff --cached --quiet HEAD || git commit -m "save" && git status && git push origin HEAD
