name: Scheduler

on:
  push
  # schedule:
  #   # 0:00 every day
  #   - cron: "0 0 * * *"

jobs:
  save:
    name: download pdf, save menu json
    runs-on: ubuntu-latest
    env:
      REPO: https://kobakazu0429:${{github.token}}@github.com/kobakazu0429/dorm_menu_bot-with_github_actions.git
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: start # will run `yarn test` command
      - name: run multi command
        run: |
          git config --global user.email "someone@sample.com"
          git config --global user.name "github workflow"
          git remote set-url origin ${REPO}
          git add .
          git commit -m 'save'
          git status
          git push origin HEAD
