name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "13.14.0"
      - run: yarn install
      - run: yarn lint
      - run: yarn test
